X=MsgBox("A virus has been detected on your computer!",0+48,"Windows Defender")
X=MsgBox("Do you want to remove it?",4+16,"Windows Defender")
X=MsgBox("Failed to remove virus. Want to try again?",4+64,"Windows Defender")
X=MsgBox("Failed to permanently delete! Please contact a system administrator as soon as possible",0+16,"Windows Defender")
X=MsgBox("Trojan.Generic.EXE has been launched",0+16,"U3VwZXIgU2NhcnkgVmlydXM")
X=MsgBox("Bypassing administrative restrictions...",0+64,"U3VwZXIgU2NhcnkgVmlydXM")
X=MsgBox("Bypass failed! Attempting another bypass...",0+64,"U3VwZXIgU2NhcnkgVmlydXM")
X=MsgBox("Bypass success! Administrative permissions have been unlocked.",0+64,"U3VwZXIgU2NhcnkgVmlydXM")
X=MsgBox("Copying files to external server",0+64,"U3VwZXIgU2NhcnkgVmlydXM")
X=MsgBox("Unauthorized breach has been detected! Attempting to fix...",0+64,"Windows Defender")
X=MsgBox("Antivirus software has been detected... Bypassing restriction[s]...",0+64,"U3VwZXIgU2NhcnkgVmlydXM")
X=MsgBox("Bypass successful! Copying all files to an external source...",0+64,"U3VwZXIgU2NhcnkgVmlydXM")
X=MsgBox("Finished.",0+64,"U3VwZXIgU2NhcnkgVmlydXM")
X=MsgBox("Initiating computer shutdown...",0+64,"U3VwZXIgU2NhcnkgVmlydXM")
X=MsgBox("Warning! Your computer has been forced to shutdown. Initiating defense protocols...",0+16,"Windows Defender")
set shell=CreateObject("Wscript.Shell")
shell.run"shutdown.exe -s -t 00"
